### ISSUE TITLE
Error in print-directions

### ISSUE THREAD

**Issue by ARROCAL** [driskull/print-directions#2]
Hello;

One question please.

In my WAB project I have this:

printPage: "https://xxxxxxxx.:3344/webappbuilder/apps/6/widgets/Directions/print-directions/index.html

and i have created a print-directions folder with all file and subfolder like this https://github.com/driskull/print-directions, but when i click in the print button this error occurs in the console when the print page is displayed:

Request URL:https://xxxxxxxx:3344/webappbuilder/apps/6/widgets/Directions/print-directions/tpl/directions
Request Method:GET
Status Code:404 Not Found

But in print-directions/tpl folder there is a directions.html file 

Do you know what I'm doing wrong?

Best regards.

**Comment by driskull** [comment]
I think you probably need to point the location to:

```
https://xxxxxxxx:3344/webappbuilder/apps/6/widgets/Directions/print-directions/tpl/directions/directions.html
```

**Comment by ARROCAL** [comment]
Hello Matt;

I'm using your print template in a WAB  widget, and the solution for my error was  change this line in print.js:
"dojo/text!template/directions" 
for this:
"dojo/text!template/directions.html".

Best regards.

**Comment by driskull** [comment]
Thanks!
